# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "easy_mail_preview"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["HowAboutWe"]
  s.date = "2012-06-08"
  s.description = "Easy previews of HTML emails for your Rails app."
  s.email = "dev@howaboutwe.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/images/easy_mail_preview/.gitkeep",
    "app/assets/javascripts/easy_mail_preview/application.js",
    "app/assets/javascripts/easy_mail_preview/emails.js",
    "app/assets/stylesheets/easy_mail_preview/application.css",
    "app/assets/stylesheets/easy_mail_preview/emails.scss",
    "app/controllers/easy_mail_preview/application_controller.rb",
    "app/controllers/easy_mail_preview/emails_controller.rb",
    "app/helpers/easy_mail_preview/application_helper.rb",
    "app/helpers/easy_mail_preview/emails_helper.rb",
    "app/views/easy_mail_preview/emails/index.html.erb",
    "app/views/layouts/easy_mail_preview/application.html.erb",
    "config/routes.rb",
    "easy_mail_preview.gemspec",
    "lib/easy_mail_preview.rb",
    "lib/easy_mail_preview/engine.rb",
    "lib/easy_mail_preview/version.rb",
    "lib/tasks/easy_mail_preview_tasks.rake",
    "screenshot.jpg",
    "script/rails",
    "test/dummy/README.rdoc",
    "test/dummy/Rakefile",
    "test/dummy/app/assets/javascripts/application.js",
    "test/dummy/app/assets/stylesheets/application.css",
    "test/dummy/app/controllers/application_controller.rb",
    "test/dummy/app/helpers/application_helper.rb",
    "test/dummy/app/mailers/.gitkeep",
    "test/dummy/app/models/.gitkeep",
    "test/dummy/app/views/layouts/application.html.erb",
    "test/dummy/config.ru",
    "test/dummy/config/application.rb",
    "test/dummy/config/boot.rb",
    "test/dummy/config/database.yml",
    "test/dummy/config/environment.rb",
    "test/dummy/config/environments/development.rb",
    "test/dummy/config/environments/production.rb",
    "test/dummy/config/environments/test.rb",
    "test/dummy/config/initializers/backtrace_silencers.rb",
    "test/dummy/config/initializers/inflections.rb",
    "test/dummy/config/initializers/mime_types.rb",
    "test/dummy/config/initializers/secret_token.rb",
    "test/dummy/config/initializers/session_store.rb",
    "test/dummy/config/initializers/wrap_parameters.rb",
    "test/dummy/config/locales/en.yml",
    "test/dummy/config/routes.rb",
    "test/dummy/lib/assets/.gitkeep",
    "test/dummy/log/.gitkeep",
    "test/dummy/public/404.html",
    "test/dummy/public/422.html",
    "test/dummy/public/500.html",
    "test/dummy/public/favicon.ico",
    "test/dummy/script/rails",
    "test/easy_mail_preview_test.rb",
    "test/functional/easy_mail_preview/emails_controller_test.rb",
    "test/integration/navigation_test.rb",
    "test/test_helper.rb",
    "test/unit/helpers/easy_mail_preview/emails_helper_test.rb"
  ]
  s.homepage = "http://github.com/howaboutwe/easy_mail_preview"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Easy previews of HTML emails for your Rails app."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<easy_mail_preview>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<easy_mail_preview>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<easy_mail_preview>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

